#!/usr/bin/env bash

# This tools has a few dependencies:
#   pass
#   node
#   make
#   xclip
#   "shellcheck
#   notify-send (libnotify)

shopt -s nullglob globstar

source ./src/notification.bash
source ./src/clip.bash
source ./src/get-password-list.bash
source ./src/check-cache-file.bash
source ./src/add-password.bash
source ./src/generate-password.bash
source ./src/select-password.bash
source ./src/select-password-action.bash

function main {
  local password_list cache_file_path last_password password

  password_list="$(get_password_list)"

  cache_file_path=$HOME/.cache/passman/cache
  check_cache_file "$cache_file_path"

  last_password="$(cat "$cache_file_path")"
  password=$(select_password "$last_password" "$password_list")

  # There is nothing left to do, if user didn't select an option
  if [[ -z $password ]]; then
    exit
  fi

  # When a password has been selected, put it to the top of the list for
  # faster reselection next time
  echo "$password" > "$cache_file_path"

  # Select the account for the selected password
  select_password_action "$password"
}

main
exit
