#!/usr/bin/env bash

# Dependencies for general usage
#   pass
#   xclip
#   notify-send (libnotify)

# Additional dependencies for development
#   node
#   make
#   Shellcheck

shopt -s nullglob globstar

source ./notification.bash
source ./clip.bash
source ./check-dependencies.bash
source ./get-password-list.bash
source ./check-cache-file.bash
source ./add-password.bash
source ./generate-password.bash
source ./select-password.bash
source ./select-password-action.bash

function main {
  local password_list cache_file_path last_password password

  check_dependencies

  password_list="$(get_password_list)"

  cache_file_path=$HOME/.cache/passman/cache
  check_cache_file "$cache_file_path"

  last_password="$(cat "$cache_file_path")"
  password=$(select_password "$last_password" "$password_list")

  # There is nothing left to do, if user didn't select an option
  if [[ -z $password ]]; then
    exit
  fi

  # When a password has been selected, put it to the top of the list for
  # faster reselection next time
  echo "$password" > "$cache_file_path"

  # Select the account for the selected password
  select_password_action "$password"
}

main
exit
